### ISSUE TITLE
Mix Bus Actions not shown in Action List

### ISSUE THREAD

**Issue by alpha-io** [bitfocus/companion-module-yamaha-scp#1]
Running 1.3.0-e1de752-1377 with Yamaha QL 1

Mix Bus actions are not shown in the dropdown menu when editing Buttons.

Log view gives the right type of Desk and amount of Mix busses.

**Comment by PTGitHubber** [comment]
Possible issue with code in lines 406 and 410 causing this issue?

In both lines, current code says Matrix although they are under sections for Mix On and Mix Off.

(Also, probably not related, and I have no idea if this is causing any issues elsewhere, but line 68 reads "function getmatix" instead of "function getmatrix". This is the only place where I see a reference to "matrix" that is missing the "r".

**Comment by JeffreyDavidsz** [comment]
406 & 410 seems to be just a typo on the label. the actual command is `set MIXER:Current/Mtrx/Fader/On '+ opt.Ch + ' 0 1`

**Comment by JeffreyDavidsz** [comment]
on line 68 there's also a typo, but also not an issue for the command being send:
`function getmatixbus(){
    self.socket.send('devinfo matrixbus' + "\n");
}`
It's being called once;
`setTimeout(getmatixbus, 2000);`

**Comment by JeffreyDavidsz** [comment]
I don't have a actual mixer, so it's hard to tell. I see that the request is made like auxbusses and matrixbusses. You said the Mix Bus Count is correct? Than the var `mixbus` is filled and the `mixbusopt` also. Try to email the developer, so he can test it

**Comment by krocheck** [comment]
@JackLongden if I recall, you developed against a TF and so some of the QL/CL variances didn't get 100% flushed out?  Or did they?

I'm trying to get a few module updates pushed out this week, then I could take a look at the specs to see what's going on here.

**Comment by JackLongden** [comment]
Yes it looks like a typo is causing this, I will look through the code over the next few days and iron out the creases. Finally got my laptop back up and running and have some time to look at code again!

**Comment by MeestorX** [comment]
The new version should support DCA functions properly. Please try it and let me know.
