### ISSUE TITLE
Channel to Matrix Settings Missing

### ISSUE THREAD

**Issue by kernelstearns** [bitfocus/companion-module-yamaha-scp#15]
I can't find any settings for channel sends on to matrices.  This would be super helpful if you can add it!

**Comment by MeestorX** [comment]
InCh/ToMtrx/On is channel send to matrix on/off
InCh/ToMtrx/Level is channel send to matrix level.

I would highly recommend using the Macro function to find commands. It's much easier than looking through the dropdown list.

http://www.checkcheckonetwo.com/forum/showthread.php?1726-How-to-create-a-Macro-in-SCP-module

**Comment by kernelstearns** [comment]
That's weird, I tried using macros to record the matrix being turned on, but it didn't record anything.

**Comment by MeestorX** [comment]
With the console connected? II assume you followed the procedure from the video?
I haven't had any problems with it, but if you are finding that Macros aren't recording as they should please let me know.

**Comment by kernelstearns** [comment]
I disconnected and reconnected the console and the options showed back up.
