### ISSUE TITLE
Matrix references limited to 4

### ISSUE THREAD

**Issue by kernelstearns** [bitfocus/companion-module-yamaha-scp#16]
The input field for matrices is currently limited to 4, but the Yamaha QL5 has support for 8 matrices.

**Comment by MeestorX** [comment]
Thank you for that feedback. 
Which action specifically? I just checked a few and they were allowing Matrices 1-8 to be selected.

**Comment by kernelstearns** [comment]
It was in Mtrx/Fader/On and Mtrx/Fader/Level.

**Comment by kernelstearns** [comment]
Just got to wondering - is this module up to date in Companion 2.0.0? That's what I'm running.

**Comment by MeestorX** [comment]
Both those allow selection of 1-8 on my machine.
Latest version of the SCP module is 1.4 which is what is shown on the GitHub site. Click the "?" on your instance to check the version.
However, I don't ever remember changing the code to in the Matrix functions so I dunno.
Happy to do a screenshare with you to figure out what's going on if it continues to give you trouble...

**Comment by kernelstearns** [comment]
I appreciate it! I won't be back in the building where I'm setting it up until tomorrow, I'll check the version and work on it some some more but I'll let you know if I need help, thanks!

**Comment by MeestorX** [comment]
No problem. If you're troubleshooting and need to go back and forth, I would recommend contacting me via my website or posting on the forum. That will also help others that might be having similar issues.

**Comment by kernelstearns** [comment]
Problem resolved.  I removed the Yamaha QL5 and added it fresh into Companion, and the options showed back up.
