### ISSUE TITLE
Yamaha CL/QL - Please add Input and mute to the mix sends Bus.

### ISSUE THREAD

**Issue by RockyRoadAudio** [bitfocus/companion-module-yamaha-scp#19]
In the companion control panel for Yamaha CL & QL is it possible to add input and mute to the mix sends bus? In the same functionality as is programmed for M32 & X32.

Thank you
Rocky

**Comment by MeestorX** [comment]
Not sure I understand what you mean by "input and mute to the mix sends bus"? There are input mutes and mix mutes already so you must mean something else?

**Comment by RockyRoadAudio** [comment]
Hi, What I mean is, if you look at the companion instance for X32/M32 you have options like "Set mute for channel to bus send" or "Set level of channel to bus send". The companion instance for Yamaha don't have these. These two commands are really useful. Sometimes I want to mute a channel to a particular mix but it stays unmuted for other mixes at the same time. Right now the mutes are "master" mutes of a whole channel to everywhere.
![Screen Shot 2020-10-06 at 06 07 01](https://user-images.githubusercontent.com/72415503/95189736-3cb94700-079c-11eb-883c-83e704f5e7f7.png)

**Comment by MeestorX** [comment]
Use:
`InCh/ToMix/On`
and
`InCh/ToMix/Level`

**Comment by MeestorX** [comment]
If you’re not sure what the name of a command is, use a macro preset to record whatever you want to happen.

**Comment by RockyRoadAudio** [comment]
Thx very much! I don't know why I didn't see this before unless this has been added recently. Nevertheless, this is what I need. Thx for the info.

**Comment by MeestorX** [comment]
You don’t need to know the name of any command if you use macros to record them.
https://www.checkcheckonetwo.com/forum/showthread.php?1740-Creating-Macros-on-Yamaha-MIDI-module

Please close this issue if resolved.
