### ISSUE TITLE
How to find the TCP file

### ISSUE THREAD

**Issue by victormongi** [bitfocus/companion-module-yamaha-scp#20]
How to find TCP file:
Error: Cannot find module '../../tcp'
Require stack:

Thank you...

**Comment by MeestorX** [comment]
What version of Companion? (Number at the Top left of the Web UI)
What's the full error message? Do a screenshot if needed.

**Comment by istnv** [comment]
Update the companion base/core. When modules were moved from `lib/module` to `node_modules` those common files needed to move as well. You must have cloned your repo before those libraries were moved.

**Comment by MeestorX** [comment]
Can we close this?

**Comment by victormongi** [comment]
Oh, thank you for reply, 
I just clone this repo and yarn install, 
then I run node index.js,
so guys, do you have step by step how to use this module?

**Comment by victormongi** [comment]
> Can we close this?

Alright...

**Comment by MeestorX** [comment]
do you have step by step how to use this module?
https://github.com/bitfocus/companion/wiki/Installation
