### ISSUE TITLE
QL and CL Model Detection

### ISSUE THREAD

**Issue by ethan-tripp** [bitfocus/companion-module-yamaha-scp#3]
Need on/off/level adjust for: 

- input (done)
- mix (missing)
- matrix (done)
- DCA (missing)

Yamaha doesn't label any outputs/sends as an "aux" on these consoles. 

Also, for the Recall Scene command, the module asks for a "Bank" (A or B) - there are not banks of preset scenes on these consoles that I'm aware of. Recall Scene function currently broken.

**Comment by krocheck** [comment]
This would indicate that model detection is not functioning properly.  Mix and the proper scene recall is in the module, but if it doesn't parse the model info from the unit correctly those wouldn't present.  Good to know!

**Comment by ethan-tripp** [comment]
Gotcha, makes sense! Let me know if/when you'd like me to test out model detection with my CL and QL on a new build. Thanks a lot!

**Comment by ethan-tripp** [comment]
@krocheck any updates on this front? No worries if not, but let me know if I can test out any new module builds when they come.
