### ISSUE TITLE
DCA Actions Missing

### ISSUE THREAD

**Issue by ethan-tripp** [bitfocus/companion-module-yamaha-scp#4]
DCA functions needed for CL and QL models. This issue may be related to the model detection problem. 

DCA Level Adjust / DCA On / DCA Off

**Comment by lekogm** [comment]
I think it would also be great if there was a DCA assign/unassign as well. I'd love to select a channel and assign or unassign it from the stream deck quickly.

**Comment by MeestorX** [comment]
The DCA functions are all there now, with feedback. The new module has been submitted, so hopefully soon it will replace the current module. Please test it when it does and let me know if it works for you. I was only able to test functionality on a CL console, don't have a TF to test with.

**Comment by ethan-tripp** [comment]
@MeestorX thank you! Will test out the new module once it pushes out in the next build. I've only got a QL and CL to test with, though.
