### ISSUE TITLE
QL Commands Crashing Companion

### ISSUE THREAD

**Issue by ethan-tripp** [bitfocus/companion-module-yamaha-scp#8]
Been testing on both a QL1 and CL1. CL1 for the most part has been working great - haven't caused a Companion crash yet after sending basic commands. 

QL1 has crashed Companion in the following ways:

- at the beginning, had to create a new instance for the existing QL1 in order to stop crashes from any command. Didn't have to create a new instance for my CL1. 

- Command 230: Cue/InCh/On crashes every time for QL1. Works fine for CL1. 

Will update with more as testing progresses.

**Comment by MeestorX** [comment]
Thank you, Ethan. Is there any error message or something in the log when it crashes? I didn't have a QL console to test, but they SHOULD have been the same as the CL.
If you are willing, I have some software that tests the SCP functionality that if you ran might tell me more about the issue with the QL.

**Comment by ethan-tripp** [comment]
Ya, I can run that for you. Send it and instructions over.

**Comment by MeestorX** [comment]
Much appreciated. It might be a week or more before I get a chance. I made some changes and need to test it on an actual console (don't need you debugging 2 programs!). I'll be in front of a CL again next week. Hate to waste bandwidth here on this discussion, if you'd like to contact me directly? andy
at
checkcheckonetwo
dot
com

**Comment by MeestorX** [comment]
I would like to know more about how it "crashes". Error message? Anything in the log?

**Comment by ethan-tripp** [comment]
Here's the error message on the machine running Companion whenever I try to send command 230 to the QL:

Uncaught Exception:
TypeError: Cannot read property 'Index' of undefined
    at tcp.<anonymous> (/Applications/Companion_Feb3.app/Contents/Resources/app.asar/lib/module/yamaha-scp/index.js:243:78)
    at emitOne (events.js:116:13)
    at tcp.emit (events.js:211:7)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
    at addChunk (_stream_readable.js:263:12)
    at readableAddChunk (_stream_readable.js:250:11)
    at Socket.Readable.push (_stream_readable.js:208:10)
    at TCP.onread (net.js:594:20)

**Comment by ethan-tripp** [comment]
and yes, I'll shoot you an email.

**Comment by MeestorX** [comment]
Thank you. Let's troubleshoot via e-mail as they'll probably some more back-and-forth to get to the bottom of this.

**Comment by MeestorX** [comment]
Should be fixed in 1.1.2 (final testing being done before pushing)
